### ISSUE TITLE
Random Values in a field of Dataset

### ISSUE THREAD

**Issue by pratkjn30** [consultantjay/LTIMEARN#13]
How to insert random values in a field of dataset in MongoDB ?

**Comment by ST1097** [comment]
var cuisines = ["European", "French", "British", "Canadian", "Indian", "Scotish", "Brazilian", "Chinese"] 
db.restaurant.find({}, {"Cuisine":1}).forEach(function(x){db.restaurant.update({_id:x._id}, {$set:{"Cuisine":type[Math.floor(Math.random()*type.length)]}}) })

The above function will add cuisines values randomly in the cuisine field of the dataset
