### ISSUE TITLE
Find Latitude and Longitude of GeoLocation through Address

### ISSUE THREAD

**Issue by bhavsar1997** [consultantjay/LTIMEARN#3]
In my Dataset (BookMyDoctor) I'm having addresses of the clinics.
I want to mark the location of clinics on google maps for which I need coordinates(lat,long) of that address.

Example: address is : "DEENANATH M HOSPITAL, ERANDAWANA, PUNE - 41100"

I need the latitude and lonitude coordinates for this address

**Comment by tarunrawat87** [comment]
Please follow certain steps

Step1: Install node-geocoder using npm
          npm install node-geocoder

Step2: Install node express using npm
          npm install  express //Ignore this step if you had already done it

Step 3:Get Google Map API key//This is necessary
 
Step 4:Enable Geocoding API //You should not miss this

Refer this code:

var NodeGeocoder = require('node-geocoder');
var options = {
provider: 'google',
httpAdapter: 'https', 
apiKey: 'YOURGOOGLEAPIKEY',
  formatter: null         
};

var geocoder = NodeGeocoder(options);

var express=require("express");
var app=express();

app.use (function(req, res, next) {
 var data='';
req.setEncoding('utf8');
req.on('data', function(chunk) { 
data += chunk;
 });

req.on('end', function() {
req.body = data;
next();
 });
});


app.post('/getGeoLocation',function(request,response){
var json=JSON.parse(request.body);

var places=[];
for(let place of json){
places.push(place.location);
}



geocoder.batchGeocode(places, function (err, results) {
  // Return an array of type {error: false, value: []}
response.json(results);
});

}); 

 
app.listen(3000,function(){
console.log('app running on 3000 port !');
});
*********************************

Use postman to send Request

Request: http://localhost:3000/getGeoLocation
Send Raw data as
[{location:"DEENANATH M HOSPITAL, ERANDAWANA, PUNE - 41100"}]

You will get this Response
    {
        "error": null,
        "value": [
            {
                "formattedAddress": "Near Mhatre Bridge, Pune, Maharashtra 411004, India",
                "latitude": 18.5018515,
                "longitude": 73.83277509999999,
                "extra": {
                    "googlePlaceId": "ChIJAQAAQPO_wjsR92yvqVBXeIk",
                    "confidence": 0.7,
                    "premise": null,
                    "subpremise": null,
                    "neighborhood": "Pune",
                    "establishment": null
                },
                "administrativeLevels": {
                    "level1long": "Maharashtra",
                    "level1short": "MH"
                },
                "city": "Pune",
                "country": "India",
                "countryCode": "IN",
                "zipcode": "411004",
                "provider": "google"
            }
        ]
    }
]
