### ISSUE TITLE
How to store the response of a mongodb query synchronously in a variable?

### ISSUE THREAD

**Issue by makwanagaurav7** [consultantjay/LTIMEARN#4]
I try to run my test cases through mocha-chai but my test case file shows the error:-

 AssertionError: expected '' to equal 4

Here is my test case code:-

var expect = require('chai').expect;
var mongojs = require('mongojs');
var db = mongojs('pizza_res',['res']);
var data="";
function get(){
	db.res.find({city:"Bend"},function(err,res){
			data = res.length;
			done();
		});
}
describe('Test by city name count',function(){
	it('count by city',function(){
                get();
		expect(data).to.equal(4);   //line1
	});
});

I find that get() function runs asynchronously thats why data variable remains same until line1
so I want to run the mongodb query synchronously to get the desired output.

**Comment by bhavsar1997** [comment]
According to MochaJS's documentation on hooks:
before(function() {}) runs before all tests in the block.

Try This:-

var expect = require('chai').expect;
var mongojs = require('mongojs');
var db = mongojs('pizza_res',['res']);

var data = 0;
describe('Test by city name count ',function(){

	before(function (done){
   		db.res.find({city:"Bend"},function(err,res){
		data = res.length;
		done();
		});
		});

	it('count by city: ',function(){
		expect(data).to.equal(4);
	});
});
